spring:
  jpa:
    hibernate:
      naming:
        implicit-strategy: legacy-jpa
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/CouponVentage
    username: root 
    password: password  
#    driverClassName: ${vcap.services.CouponVentage-MySQL.credentials.driverclassname}
#    url: ${vcap.services.CouponVentage-MySQL.credentials.url}
#    username: ${vcap.services.CouponVentage-MySQL.credentials.username} 
#    password: ${vcap.services.CouponVentage-MySQL.credentials.password}
    dbcp:
      validation-query: SELECT 1
      test-while-idle: true
      
hibernate:
  dialect: org.hibernate.dialect.MySQLDialect
  show_sql: true
  hbm2ddl:
    auto: none